import { Country } from "@/libs/types";

type StaticCountryType = Pick<Country, "code" | "name" | "flag"> & {
  name_de: string;
};

export function countryFlag(countryName?: string | null): string | null {
  if (!countryName) {
    return null;
  }

  const country = getCountryByName(countryName);
  const flag = country?.flag;

  if (!flag) {
    return null;
  }

  return flag;
}

export function getCountryByName(name?: string | null) {
  if (!name) {
    return null;
  }

  return countries.find((country) => country.name === name);
}
export function getCountryByCode(code: string) {
  return countries.find((country) => country.code === code);
}
const countries: StaticCountryType[] = [
  {
    code: "AF",
    name: "Afghanistan",
    name_de: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    code: "AL",
    name: "Albania",
    name_de: "Albanien",
    flag: "🇦🇱",
  },
  {
    code: "DZ",
    name: "Algeria",
    name_de: "Algerien",
    flag: "🇩🇿",
  },
  {
    code: "AD",
    name: "Andorra",
    name_de: "Andorra",
    flag: "🇦🇩",
  },
  {
    code: "AO",
    name: "Angola",
    name_de: "Angola",
    flag: "🇦🇴",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    name_de: "Antigua und Barbuda",
    flag: "🇦🇬",
  },
  {
    code: "AR",
    name: "Argentina",
    name_de: "Argentinien",
    flag: "🇦🇷",
  },
  {
    code: "AM",
    name: "Armenia",
    name_de: "Armenien",
    flag: "🇦🇲",
  },
  {
    code: "AU",
    name: "Australia",
    name_de: "Australien",
    flag: "🇦🇺",
  },
  {
    code: "AT",
    name: "Austria",
    name_de: "Österreich",
    flag: "🇦🇹",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    name_de: "Aserbaidschan",
    flag: "🇦🇿",
  },
  {
    code: "BS",
    name: "Bahamas",
    name_de: "Bahamas",
    flag: "🇧🇸",
  },
  {
    code: "BH",
    name: "Bahrain",
    name_de: "Bahrain",
    flag: "🇧🇭",
  },
  {
    code: "BD",
    name: "Bangladesh",
    name_de: "Bangladesch",
    flag: "🇧🇩",
  },
  {
    code: "BB",
    name: "Barbados",
    name_de: "Barbados",
    flag: "🇧🇧",
  },
  {
    code: "BY",
    name: "Belarus",
    name_de: "Weißrussland",
    flag: "🇧🇾",
  },
  {
    code: "BE",
    name: "Belgium",
    name_de: "Belgien",
    flag: "🇧🇪",
  },
  {
    code: "BZ",
    name: "Belize",
    name_de: "Belize",
    flag: "🇧🇿",
  },
  {
    code: "BJ",
    name: "Benin",
    name_de: "Benin",
    flag: "🇧🇯",
  },
  {
    code: "BT",
    name: "Bhutan",
    name_de: "Bhutan",
    flag: "🇧🇹",
  },
  {
    code: "BO",
    name: "Bolivia",
    name_de: "Bolivien",
    flag: "🇧🇴",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    name_de: "Bosnien und Herzegowina",
    flag: "🇧🇦",
  },
  {
    code: "BW",
    name: "Botswana",
    name_de: "Botswana",
    flag: "🇧🇼",
  },
  {
    code: "BR",
    name: "Brazil",
    name_de: "Brasilien",
    flag: "🇧🇷",
  },
  {
    code: "BN",
    name: "Brunei",
    name_de: "Brunei",
    flag: "🇧🇳",
  },
  {
    code: "BG",
    name: "Bulgaria",
    name_de: "Bulgarien",
    flag: "🇧🇬",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    name_de: "Burkina Faso",
    flag: "🇧🇫",
  },
  {
    code: "BI",
    name: "Burundi",
    name_de: "Burundi",
    flag: "🇧🇮",
  },
  {
    code: "KH",
    name: "Cambodia",
    name_de: "Kambodscha",
    flag: "🇰🇭",
  },
  {
    code: "CM",
    name: "Cameroon",
    name_de: "Kamerun",
    flag: "🇨🇲",
  },
  {
    code: "CA",
    name: "Canada",
    name_de: "Kanada",
    flag: "🇨🇦",
  },
  {
    code: "CV",
    name: "Cape Verde",
    name_de: "Kap Verde",
    flag: "🇨🇻",
  },
  {
    code: "CF",
    name: "Central African Republic",
    name_de: "Zentralafrikanische Republik",
    flag: "🇨🇫",
  },
  {
    code: "TD",
    name: "Chad",
    name_de: "Tschad",
    flag: "🇹🇩",
  },
  {
    code: "CL",
    name: "Chile",
    name_de: "Chile",
    flag: "🇨🇱",
  },
  {
    code: "CN",
    name: "China",
    name_de: "China",
    flag: "🇨🇳",
  },
  {
    code: "CO",
    name: "Colombia",
    name_de: "Kolumbien",
    flag: "🇨🇴",
  },
  {
    code: "KM",
    name: "Comoros",
    name_de: "Komoren",
    flag: "🇰🇲",
  },
  {
    code: "CG",
    name: "Congo [Republic]",
    name_de: "Kongo [Republik]",
    flag: "🇨🇬",
  },
  {
    code: "CD",
    name: "Congo [DRC]",
    name_de: "Kongo [DRC]",
    flag: "🇨🇩",
  },
  {
    code: "CR",
    name: "Costa Rica",
    name_de: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    code: "HR",
    name: "Croatia",
    name_de: "Kroatien",
    flag: "🇭🇷",
  },
  {
    code: "CU",
    name: "Cuba",
    name_de: "Kuba",
    flag: "🇨🇺",
  },
  {
    code: "CY",
    name: "Cyprus",
    name_de: "Zypern",
    flag: "🇨🇾",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    name_de: "Tschechien",
    flag: "🇨🇿",
  },
  {
    code: "DK",
    name: "Denmark",
    name_de: "Dänemark",
    flag: "🇩🇰",
  },
  {
    code: "DJ",
    name: "Djibouti",
    name_de: "Dschibuti",
    flag: "🇩🇯",
  },
  {
    code: "DM",
    name: "Dominica",
    name_de: "Dominica",
    flag: "🇩🇲",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    name_de: "Dominikanische Republik",
    flag: "🇩🇴",
  },
  {
    code: "EC",
    name: "Ecuador",
    name_de: "Ecuador",
    flag: "🇪🇨",
  },
  {
    code: "EG",
    name: "Egypt",
    name_de: "Ägypten",
    flag: "🇪🇬",
  },
  {
    code: "SV",
    name: "El Salvador",
    name_de: "El Salvador",
    flag: "🇸🇻",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    name_de: "Äquatorialguinea",
    flag: "🇬🇶",
  },
  {
    code: "ER",
    name: "Eritrea",
    name_de: "Eritrea",
    flag: "🇪🇷",
  },
  {
    code: "EE",
    name: "Estonia",
    name_de: "Estland",
    flag: "🇪🇪",
  },
  {
    code: "ET",
    name: "Ethiopia",
    name_de: "Äthiopien",
    flag: "🇪🇹",
  },
  {
    code: "FJ",
    name: "Fiji",
    name_de: "Fidschi",
    flag: "🇫🇯",
  },
  {
    code: "FI",
    name: "Finland",
    name_de: "Finnland",
    flag: "🇫🇮",
  },
  {
    code: "FR",
    name: "France",
    name_de: "Frankreich",
    flag: "🇫🇷",
  },
  {
    code: "GA",
    name: "Gabon",
    name_de: "Gabun",
    flag: "🇬🇦",
  },
  {
    code: "GM",
    name: "Gambia",
    name_de: "Gambia",
    flag: "🇬🇲",
  },
  {
    code: "GE",
    name: "Georgia",
    name_de: "Georgien",
    flag: "🇬🇪",
  },
  {
    code: "DE",
    name: "Germany",
    name_de: "Deutschland",
    flag: "🇩🇪",
  },
  {
    code: "GH",
    name: "Ghana",
    name_de: "Ghana",
    flag: "🇬🇭",
  },
  {
    code: "GR",
    name: "Greece",
    name_de: "Griechenland",
    flag: "🇬🇷",
  },
  {
    code: "GD",
    name: "Grenada",
    name_de: "Grenada",
    flag: "🇬🇩",
  },
  {
    code: "GT",
    name: "Guatemala",
    name_de: "Guatemala",
    flag: "🇬🇹",
  },
  {
    code: "GN",
    name: "Guinea",
    name_de: "Guinea",
    flag: "🇬🇳",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    name_de: "Guinea-Bissau",
    flag: "🇬🇼",
  },
  {
    code: "GY",
    name: "Guyana",
    name_de: "Guyana",
    flag: "🇬🇾",
  },
  {
    code: "HT",
    name: "Haiti",
    name_de: "Haiti",
    flag: "🇭🇹",
  },
  {
    code: "HN",
    name: "Honduras",
    name_de: "Honduras",
    flag: "🇭🇳",
  },
  {
    code: "HU",
    name: "Hungary",
    name_de: "Ungarn",
    flag: "🇭🇺",
  },
  {
    code: "HK",
    name: "Hong Kong",
    name_de: "Hong Kong",
    flag: "🇭🇰",
  },
  {
    code: "IS",
    name: "Iceland",
    name_de: "Island",
    flag: "🇮🇸",
  },
  {
    code: "IN",
    name: "India",
    name_de: "Indien",
    flag: "🇮🇳",
  },
  {
    code: "ID",
    name: "Indonesia",
    name_de: "Indonesien",
    flag: "🇮🇩",
  },
  {
    code: "IR",
    name: "Iran",
    name_de: "Iran",
    flag: "🇮🇷",
  },
  {
    code: "IQ",
    name: "Iraq",
    name_de: "Irak",
    flag: "🇮🇶",
  },
  {
    code: "IE",
    name: "Ireland",
    name_de: "Irland",
    flag: "🇮🇪",
  },
  {
    code: "IL",
    name: "Israel",
    name_de: "Israel",
    flag: "🇮🇱",
  },
  {
    code: "IT",
    name: "Italy",
    name_de: "Italien",
    flag: "🇮🇹",
  },
  {
    code: "JM",
    name: "Jamaica",
    name_de: "Jamaika",
    flag: "🇯🇲",
  },
  {
    code: "JP",
    name: "Japan",
    name_de: "Japan",
    flag: "🇯🇵",
  },
  {
    code: "JO",
    name: "Jordan",
    name_de: "Jordanien",
    flag: "🇯🇴",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    name_de: "Kasachstan",
    flag: "🇰🇿",
  },
  {
    code: "KE",
    name: "Kenya",
    name_de: "Kenia",
    flag: "🇰🇪",
  },
  {
    code: "KI",
    name: "Kiribati",
    name_de: "Kiribati",
    flag: "🇰🇮",
  },
  {
    code: "KP",
    name: "North Korea",
    name_de: "Nordkorea",
    flag: "🇰🇵",
  },
  {
    code: "KR",
    name: "South Korea",
    name_de: "Südkorea",
    flag: "🇰🇷",
  },
  {
    code: "KW",
    name: "Kuwait",
    name_de: "Kuwait",
    flag: "🇰🇼",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    name_de: "Kirgisistan",
    flag: "🇰🇬",
  },
  {
    code: "LA",
    name: "Laos",
    name_de: "Laos",
    flag: "🇱🇦",
  },
  {
    code: "LV",
    name: "Latvia",
    name_de: "Lettland",
    flag: "🇱🇻",
  },
  {
    code: "LB",
    name: "Lebanon",
    name_de: "Libanon",
    flag: "🇱🇧",
  },
  {
    code: "LS",
    name: "Lesotho",
    name_de: "Lesotho",
    flag: "🇱🇸",
  },
  {
    code: "LR",
    name: "Liberia",
    name_de: "Liberia",
    flag: "🇱🇷",
  },
  {
    code: "LY",
    name: "Libya",
    name_de: "Libyen",
    flag: "🇱🇾",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    name_de: "Liechtenstein",
    flag: "🇱🇮",
  },
  {
    code: "LT",
    name: "Lithuania",
    name_de: "Litauen",
    flag: "🇱🇹",
  },
  {
    code: "LU",
    name: "Luxembourg",
    name_de: "Luxemburg",
    flag: "🇱🇺",
  },
  {
    code: "MK",
    name: "Macedonia",
    name_de: "Mazedonien",
    flag: "🇲🇰",
  },
  {
    code: "MG",
    name: "Madagascar",
    name_de: "Madagaskar",
    flag: "🇲🇬",
  },
  {
    code: "MW",
    name: "Malawi",
    name_de: "Malawi",
    flag: "🇲🇼",
  },
  {
    code: "MY",
    name: "Malaysia",
    name_de: "Malaysia",
    flag: "🇲🇾",
  },
  {
    code: "MV",
    name: "Maldives",
    name_de: "Malediven",
    flag: "🇲🇻",
  },
  {
    code: "ML",
    name: "Mali",
    name_de: "Mali",
    flag: "🇲🇱",
  },
  {
    code: "MT",
    name: "Malta",
    name_de: "Malta",
    flag: "🇲🇹",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    name_de: "Marshallinseln",
    flag: "🇲🇭",
  },
  {
    code: "MR",
    name: "Mauritania",
    name_de: "Mauretanien",
    flag: "🇲🇷",
  },
  {
    code: "MU",
    name: "Mauritius",
    name_de: "Mauritius",
    flag: "🇲🇺",
  },
  {
    code: "MX",
    name: "Mexico",
    name_de: "Mexiko",
    flag: "🇲🇽",
  },
  {
    code: "FM",
    name: "Micronesia",
    name_de: "Mikronesien",
    flag: "🇫🇲",
  },
  {
    code: "MD",
    name: "Moldova",
    name_de: "Moldawien",
    flag: "🇲🇩",
  },
  {
    code: "MC",
    name: "Monaco",
    name_de: "Monaco",
    flag: "🇲🇨",
  },
  {
    code: "MN",
    name: "Mongolia",
    name_de: "Mongolei",
    flag: "🇲🇳",
  },
  {
    code: "ME",
    name: "Montenegro",
    name_de: "Montenegro",
    flag: "🇲🇪",
  },
  {
    code: "MA",
    name: "Morocco",
    name_de: "Marokko",
    flag: "🇲🇦",
  },
  {
    code: "MZ",
    name: "Mozambique",
    name_de: "Mosambik",
    flag: "🇲🇿",
  },
  {
    code: "MM",
    name: "Myanmar",
    name_de: "Myanmar",
    flag: "🇲🇲",
  },
  {
    code: "NA",
    name: "Namibia",
    name_de: "Namibia",
    flag: "🇳🇦",
  },
  {
    code: "NR",
    name: "Nauru",
    name_de: "Nauru",
    flag: "🇳🇷",
  },
  {
    code: "NP",
    name: "Nepal",
    name_de: "Nepal",
    flag: "🇳🇵",
  },
  {
    code: "NL",
    name: "Netherlands",
    name_de: "Niederlande",
    flag: "🇳🇱",
  },
  {
    code: "NZ",
    name: "New Zealand",
    name_de: "Neuseeland",
    flag: "🇳🇿",
  },
  {
    code: "NI",
    name: "Nicaragua",
    name_de: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    code: "NE",
    name: "Niger",
    name_de: "Niger",
    flag: "🇳🇪",
  },
  {
    code: "NG",
    name: "Nigeria",
    name_de: "Nigeria",
    flag: "🇳🇬",
  },
  {
    code: "NO",
    name: "Norway",
    name_de: "Norwegen",
    flag: "🇳🇴",
  },
  {
    code: "OM",
    name: "Oman",
    name_de: "Oman",
    flag: "🇴🇲",
  },
  {
    code: "PK",
    name: "Pakistan",
    name_de: "Pakistan",
    flag: "🇵🇰",
  },
  {
    code: "PW",
    name: "Palau",
    name_de: "Palau",
    flag: "🇵🇼",
  },
  {
    code: "PA",
    name: "Panama",
    name_de: "Panama",
    flag: "🇵🇦",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    name_de: "Papua-Neuguinea",
    flag: "🇵🇬",
  },
  {
    code: "PY",
    name: "Paraguay",
    name_de: "Paraguay",
    flag: "🇵🇾",
  },
  {
    code: "PE",
    name: "Peru",
    name_de: "Peru",
    flag: "🇵🇪",
  },
  {
    code: "PH",
    name: "Philippines",
    name_de: "Philippinen",
    flag: "🇵🇭",
  },
  {
    code: "PL",
    name: "Poland",
    name_de: "Polen",
    flag: "🇵🇱",
  },
  {
    code: "PT",
    name: "Portugal",
    name_de: "Portugal",
    flag: "🇵🇹",
  },
  {
    code: "QA",
    name: "Qatar",
    name_de: "Katar",
    flag: "🇶🇦",
  },
  {
    code: "RO",
    name: "Romania",
    name_de: "Rumänien",
    flag: "🇷🇴",
  },
  {
    code: "RU",
    name: "Russia",
    name_de: "Russland",
    flag: "🇷🇺",
  },
  {
    code: "RW",
    name: "Rwanda",
    name_de: "Ruanda",
    flag: "🇷🇼",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    name_de: "St. Kitts und Nevis",
    flag: "🇰🇳",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    name_de: "St. Lucia",
    flag: "🇱🇨",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    name_de: "St. Vincent und die Grenadinen",
    flag: "🇻🇨",
  },
  {
    code: "WS",
    name: "Samoa",
    name_de: "Samoa",
    flag: "🇼🇸",
  },
  {
    code: "SM",
    name: "San Marino",
    name_de: "San Marino",
    flag: "🇸🇲",
  },
  {
    code: "ST",
    name: "São Tomé and Príncipe",
    name_de: "São Tomé und Príncipe",
    flag: "🇸🇹",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    name_de: "Saudi-Arabien",
    flag: "🇸🇦",
  },
  {
    code: "SN",
    name: "Senegal",
    name_de: "Senegal",
    flag: "🇸🇳",
  },
  {
    code: "RS",
    name: "Serbia",
    name_de: "Serbien",
    flag: "🇷🇸",
  },
  {
    code: "SC",
    name: "Seychelles",
    name_de: "Seychellen",
    flag: "🇸🇨",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    name_de: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    code: "SG",
    name: "Singapore",
    name_de: "Singapur",
    flag: "🇸🇬",
  },
  {
    code: "SK",
    name: "Slovakia",
    name_de: "Slowakei",
    flag: "🇸🇰",
  },
  {
    code: "SI",
    name: "Slovenia",
    name_de: "Slowenien",
    flag: "🇸🇮",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    name_de: "Salomonen",
    flag: "🇸🇧",
  },
  {
    code: "SO",
    name: "Somalia",
    name_de: "Somalia",
    flag: "🇸🇴",
  },
  {
    code: "ZA",
    name: "South Africa",
    name_de: "Südafrika",
    flag: "🇿🇦",
  },
  {
    code: "SS",
    name: "South Sudan",
    name_de: "Südsudan",
    flag: "🇸🇸",
  },
  {
    code: "ES",
    name: "Spain",
    name_de: "Spanien",
    flag: "🇪🇸",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    name_de: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    code: "SD",
    name: "Sudan",
    name_de: "Sudan",
    flag: "🇸🇩",
  },
  {
    code: "SR",
    name: "Suriname",
    name_de: "Suriname",
    flag: "🇸🇷",
  },
  {
    code: "SZ",
    name: "Swaziland",
    name_de: "Swasiland",
    flag: "🇸🇿",
  },
  {
    code: "SE",
    name: "Sweden",
    name_de: "Schweden",
    flag: "🇸🇪",
  },
  {
    code: "CH",
    name: "Switzerland",
    name_de: "Schweiz",
    flag: "🇨🇭",
  },
  {
    code: "SY",
    name: "Syria",
    name_de: "Syrien",
    flag: "🇸🇾",
  },
  {
    code: "TW",
    name: "Taiwan",
    name_de: "Taiwan",
    flag: "🇹🇼",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    name_de: "Tadschikistan",
    flag: "🇹🇯",
  },
  {
    code: "TZ",
    name: "Tanzania",
    name_de: "Tansania",
    flag: "🇹🇿",
  },
  {
    code: "TH",
    name: "Thailand",
    name_de: "Thailand",
    flag: "🇹🇭",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    name_de: "Timor-Leste",
    flag: "🇹🇱",
  },
  {
    code: "TG",
    name: "Togo",
    name_de: "Togo",
    flag: "🇹🇬",
  },
  {
    code: "TO",
    name: "Tonga",
    name_de: "Tonga",
    flag: "🇹🇴",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    name_de: "Trinidad und Tobago",
    flag: "🇹🇹",
  },
  {
    code: "TN",
    name: "Tunisia",
    name_de: "Tunesien",
    flag: "🇹🇳",
  },
  {
    code: "TR",
    name: "Turkey",
    name_de: "Türkei",
    flag: "🇹🇷",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    name_de: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    code: "TV",
    name: "Tuvalu",
    name_de: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    code: "UG",
    name: "Uganda",
    name_de: "Uganda",
    flag: "🇺🇬",
  },
  {
    code: "UA",
    name: "Ukraine",
    name_de: "Ukraine",
    flag: "🇺🇦",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    name_de: "Vereinigte Arabische Emirate",
    flag: "🇦🇪",
  },
  {
    code: "GB",
    name: "United Kingdom",
    name_de: "Vereinigtes Königreich",
    flag: "🇬🇧",
  },
  {
    code: "US",
    name: "United States",
    name_de: "Vereinigte Staaten",
    flag: "🇺🇸",
  },
  {
    code: "UY",
    name: "Uruguay",
    name_de: "Uruguay",
    flag: "🇺🇾",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    name_de: "Usbekistan",
    flag: "🇺🇿",
  },
  {
    code: "VU",
    name: "Vanuatu",
    name_de: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    code: "VA",
    name: "Vatican City",
    name_de: "Vatikanstadt",
    flag: "🇻🇦",
  },
  {
    code: "VE",
    name: "Venezuela",
    name_de: "Venezuela",
    flag: "🇻🇪",
  },
  {
    code: "VN",
    name: "Vietnam",
    name_de: "Vietnam",
    flag: "🇻🇳",
  },
  {
    code: "YE",
    name: "Yemen",
    name_de: "Jemen",
    flag: "🇾🇪",
  },
  {
    code: "ZM",
    name: "Zambia",
    name_de: "Sambia",
    flag: "🇿🇲",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    name_de: "Simbabwe",
    flag: "🇿🇼",
  },
];

export default countries;

