export const lastUpdated = "2024-12-11";
export const address = "Waldstr. 48, 90763 Fürth, Germany";

export const unsplashCredits = [
    'Photo by <a href="https://unsplash.com/@stewi?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Stephan Widua</a> on <a href="https://unsplash.com/photos/time-lapse-photography-of-vehicle-at-the-road-in-between-the-building-at-nighttime-aerial-photography-iPOZf3tQfHA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
    'Photo by <a href="https://unsplash.com/@jankolar?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jan Antonin Kolar</a> on <a href="https://unsplash.com/photos/view-of-buildings-8QJSi37vhms?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
    'Photo by <a href="https://unsplash.com/@kumas_taverne?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">𝕶𝖚𝖒𝖆𝖘 𝕿𝖆𝖛𝖊𝖗𝖓𝖊</a> on <a href="https://unsplash.com/photos/a-water-fountain-in-front-of-a-large-building-5TvIkh12MSA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
    'Photo by Philipp Birmes: https://www.pexels.com/photo/worms-eye-view-of-high-rise-building-3646913/',
    'Photo by Jasper Kortmann: https://www.pexels.com/photo/view-of-cologne-cathedral-and-hohenzollern-bridge-29693403/',
    'Photo by Pixabay: https://www.pexels.com/photo/view-of-skyscrapers-against-cloudy-sky-258642/',
    'Image by <a href="https://pixabay.com/users/maxmann-665103/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=2890738">Th G</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=2890738">Pixabay</a>',
    'Bild von <a href="https://pixabay.com/de/users/waldnob-9842518/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6935921">Norbert Waldhausen</a> auf <a href="https://pixabay.com/de//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6935921">Pixabay</a>',
    'Bild von <a href="https://pixabay.com/de/users/schaerfsystem-130387/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=745365">Caro Sodar</a> auf <a href="https://pixabay.com/de//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=745365">Pixabay</a>',
    'Image by <a href="https://pixabay.com/users/evgenit-4930349/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3150867">Evgeni Tcherkasski</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3150867">Pixabay</a>',
    'Image by <a href="https://pixabay.com/users/maxmann-665103/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1055063">Th G</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1055063">Pixabay</a>',
    'Photo by Markus Spiske: https://www.pexels.com/photo/brown-wooden-table-and-chairs-93108/',
    'Image by <a href="https://pixabay.com/users/medienservice-1888061/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6557996">Nicole Pankalla</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=6557996">Pixabay</a>',
    'Image by <a href="https://pixabay.com/users/kookay-11914957/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4152279">Udo</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4152279">Pixabay</a>',
    'Image by <a href="https://pixabay.com/users/unlike_you_photography-12470727/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4206677">Andreas Poznanski</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4206677">Pixabay</a>',
    'Photo by Jakub Zerdzicki: https://www.pexels.com/photo/bochum-rathaus-station-21625033/',
    'Image by <a href="https://pixabay.com/users/mibro-8455312/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3352209">mibro</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3352209">Pixabay</a>',
    'Image by <a href="https://pixabay.com/users/marcimarc105-6128323/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3913173">Marci Marc</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3913173">Pixabay</a>',
    'Image by <a href="https://pixabay.com/users/tomkor-20122445/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=5974157">tomkor</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=5974157">Pixabay</a>',
    'Photo by Robert Schwarz: https://www.pexels.com/photo/a-suspension-railway-entering-a-station-27775590/',
    'Photo by <a href="https://unsplash.com/@ti_fuerth?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Tourist-Information Fürth</a> on <a href="https://unsplash.com/photos/a-large-clock-tower-towering-over-a-city-2nWM9yYt8UI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  ]